//
// Balance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Balance: Codable {

    public var balanceString: String
    public var balanceValue: Double

    public init(balanceString: String, balanceValue: Double) {
        self.balanceString = balanceString
        self.balanceValue = balanceValue
    }

}

