//
// Card.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Card: Codable {

    public var id: Int64
    public var name: String
    public var spentString: String
    public var spentValue: Double
    public var availableString: String
    public var availableValue: Double

    public init(id: Int64, name: String, spentString: String, spentValue: Double, availableString: String, availableValue: Double) {
        self.id = id
        self.name = name
        self.spentString = spentString
        self.spentValue = spentValue
        self.availableString = availableString
        self.availableValue = availableValue
    }

}

