//
// Investment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Investment: Codable {

    public var id: Int64
    public var name: String
    public var description: String
    public var iOSImage: String

    public init(id: Int64, name: String, description: String, iOSImage: String) {
        self.id = id
        self.name = name
        self.description = description
        self.iOSImage = iOSImage
    }

}

