//
// MyInvestments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MyInvestments: Codable {

    public var balance: String
    public var investments: [MyInvestment]

    public init(balance: String, investments: [MyInvestment]) {
        self.balance = balance
        self.investments = investments
    }

}

