//
// MyInvestment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MyInvestment: Codable {

    public var id: Int64
    public var name: String
    public var balanceString: String
    public var balanceValue: Double
    public var iOSImage: String

    public init(id: Int64, name: String, balanceString: String, balanceValue: Double, iOSImage: String) {
        self.id = id
        self.name = name
        self.balanceString = balanceString
        self.balanceValue = balanceValue
        self.iOSImage = iOSImage
    }

}

