//
// MyInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MyInfo: Codable {

    public var name: String
    public var email: String
    public var cpf: String
    public var phone: String
    public var bank: String
    public var agency: String
    public var account: String

    public init(name: String, email: String, cpf: String, phone: String, bank: String, agency: String, account: String) {
        self.name = name
        self.email = email
        self.cpf = cpf
        self.phone = phone
        self.bank = bank
        self.agency = agency
        self.account = account
    }

}

